name: deploy to Prod

on:
  push:
    branches: [prod]

jobs:
  worker:
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners
    runs-on: ubuntu-18.04
    steps:
      - name: Get code
        uses: actions/checkout@v2

      # https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows
      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install
        run: npm ci

      - name: Build
        run: npm run application:build:prod

      - name: Release
        if: success()
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Configure AWS credentials
        if: success()
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Remove files to the application with the AWS CLI
        if: success()
        run: |
          aws s3 rm s3://${{ secrets.AWS_S3_APPLICATION_BUKET }} --recursive

      - name: Copy files to the application with the AWS CLI
        if: success()
        run: |
          aws s3 sync ./www s3://${{ secrets.AWS_S3_APPLICATION_BUKET }} --acl public-read

      - name: Invalidation distribution with the AWS CLI
        if: success()
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_KEY }} --paths '/*'